### PR TITLE
Keep generic types when fork-ing

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/dart-lang/angular_test/issues/9

### CODE REVIEW

**Comment by matanlurey** [comment]
Tiny ping.

**Comment by matanlurey** [comment]
/tbr @hterkelsen or @natebosch, as this is blocking a future sync.

**Review by natebosch — COMMENTED** [review]
LGTM

**Review by harryterkelsen — COMMENTED** [review]
lgtm

**Pull request merged**
