### PR TITLE
Prepare for 1.0.0-beta+3.

### PR DESCRIPTION
**Pull request by matanlurey**

### CODE REVIEW

**Comment by matanlurey** [comment]
Hmm, @kevmoo anything I did wrong? I see:

> $ pub get
> Resolving dependencies... (1.7s)
> Package angular2 has no versions that match >=3.0.0-beta+1 <4.0.0 derived from:
> - angular_test depends on version >=3.0.0-beta+1 <4.0.0

**Comment by kevmoo** [comment]
> anything I did wrong? I see:

Need to nuke stable/1.22.1 – not support w/ latest angular

**Comment by kevmoo** [comment]
@matanlurey we need to get back to this – needed for testing Angular

CC @grouma

**Comment by matanlurey** [comment]
Superceded by https://github.com/dart-lang/angular_test/pull/68

**Pull request closed without merging**
